steps:
- name: node:12.12.0
  entrypoint: npm
  args:
  - 'install'

- name: node:12.12.0
  entrypoint: npm
  args:
  - 'run'
  - 'build'

- name: 'gcr.io/xenon-burner-256414/firebase'
  args:
  - 'deploy'
  secretEnv:
  - 'FIREBASE_TOKEN'

secrets:
- kmsKeyName: projects/xenon-burner-256414/locations/global/keyRings/GarboScore/cryptoKeys/deploy
  secretEnv:
    FIREBASE_TOKEN: CiQAx5eBXAFn0Bm/oL2wUhdJIvK0jfmQxABGDtvJwUjUb50D52gSkAEARqGCx4+3eKiesAlQ9qATg+69tmgfltcCLVBn3KkU7jbAPFDtuI/ZzUjMiis/DrxKejhFAw68z8ByAvqv9UnLxh5fX71OrWdCqaF1XsWdUlSBxENo26fzn2V5bEE22UOIWoYXVHWd0s1SxUEkSNrvce8b0mjpHJN5xRBzPGe3NGeVAJWat1F9bvVRZ0uoTAg=
